name: 🌍 New Translation Submission
description: Submit a new or improved language file for PandaGarage
labels: ["translation", "contribution"]
body:
  - type: input
    id: language
    attributes:
      label: Language Name
      placeholder: e.g. German
    validations:
      required: true

  - type: input
    id: locale
    attributes:
      label: Locale Code
      placeholder: e.g. de
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Please attach your translation file (e.g. `de.json`) by dragging and dropping it into *Paste, drop, or click to add files* section below the Notes field.

  - type: textarea
    id: notes
    attributes:
      label: Notes (optional)
      placeholder: Any context or notes for this translation