name: Release Firmware on Label

on:
  pull_request:
    types: [closed]

jobs:
  release:
    if: github.event.pull_request.merged == true &&
        contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install PlatformIO
      run: pip install platformio

    - name: Extract firmware version from config.h
      id: firmware_version
      run: |
        VERSION=$(grep -oP '#define\s+VERSION\s+"\K[^"]+' src/config.h)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Firmware version: $VERSION"

    - name: Extract filesystem version
      id: fs_version
      run: |
        FS_VERSION=$(cat data/version.txt | tr -d '\n')
        echo "FS_VERSION=$FS_VERSION" >> $GITHUB_ENV
        echo "Filesystem version: $FS_VERSION"

    - name: Build firmware
      run: pio run -e HW-2

    - name: Build filesystem
      run: pio run -e HW-2 -t buildfs

    - name: Rename binaries with version
      run: |
        mkdir release
        cp .pio/build/HW-2/firmware.bin release/firmware-${VERSION}.bin
        cp .pio/build/HW-2/littlefs.bin release/filesystem-${FS_VERSION}.bin

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.VERSION }}
        name: ${{ env.VERSION }}
        draft: true
        files: release/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
